### ISSUE TITLE
Unwanted characters appear during combinations

### ISSUE THREAD

**Issue by simfender** [dabonetn/C64USBKey#2]
I'm actually writing this issue report with the c64 keyboard, so when I try to write, for instance "XD" quickly with the shift key pressed, the character "A" will appear in the middle, ex: XAD

I do not know if there are other combinations that are affected.

I'm using Arduino Leonardo and Windows 7.

**Comment by dabonetn** [comment]
Yep, I just verified the bug, and that it existed in the original version by Pyofer, 
And seems to be active when shift is pressed, but not unshifted.

So I' don't know where it's coming from. I can tell you that it seems to follow the keyboard set selected. And in the current version, it's the 12th value that it's inserting randomly.

In the original sketch, it was the 10th.

Maybe a real programmer can take a look?

**Comment by dabonetn** [comment]
Ok, The problem has been isolated to hardware ghosting, and isn't possible to really fix in software. 

Here's what I found about the original 64.

> Limitations
The technical limitation on the C64 Keyboard hardware is that not more than 2 keys may be pressed at the same time if you want to be 100% sure the result is valid. In some cases, three keys will work fine but whenever 3 keys form a right angle in the keyboard scan matrix, a 4th letter will appear. The combination “ABC” will work fine but the combination “ASD” will form such a triangle and the matrix will also report that the “F” key is pressed. Same goes for “ASF” which would incorrectly read a “D” the same way.
> 

So the XD combo results in a extra A when the left shift is used, but correct when the right shift is used.
Other key combos are also affected. So I guess, don't use more than 2 keys at a time or watch what you are typing...
