### ISSUE TITLE
2° Fire Button for Joystick

### ISSUE THREAD

**Issue by Denara68** [dabonetn/C64USBKey#3]
Why not a second fire button?
So you can easily play Amiga\Msx\Amstrad and other 8/16bit pc.
Other question is about Keyboard Pin1 and Keyboard Pin14. Do I connect them to Arduino "11 8 - A8"  ???
--

**Comment by dabonetn** [comment]
Done, see the new source

**Comment by Denara68** [comment]
Thanks, I'll try this



Il giorno sab 19 gen 2019 alle ore 22:33 dabonetn <notifications@github.com>
ha scritto:
