### ISSUE TITLE
German umlaut ä/Ä on Semicolon (KEY_QUOTE) Shifted / Unshifted = always "Ä"

### ISSUE THREAD

**Issue by hpingel** [dabonetn/C64USBKey#4]
Hi dabone,

You have asked for feedback from Europe: I'm currently testing C64USBKey and I like it. Thank you for your work!
(Side note: I have started a thread in forum64.de about C64USBKey so there might be more feedback coming in in future: https://www.forum64.de/index.php?thread/87674-c64usbkey-c64-usb-keyboard-mit-arduino-pro-micro-oder-teensy-lc/)

I have tested C64USBKey with the default settings (unchanged sourcecode) and with a C64 keyboard attached (without Joysticks) to my Pro Micro.  My OS on the PC is set to German Language Keyboard. I testes with Windows 10 and Linux - in both cases with a simple text editor (not Vice Emu).

One thing that I noticed is about KEY_SEMICOLON (Two positions left of the RETURN key): When I press the key without holding SHIFT I expect lower case "ä" but instead I get upper case "Ä". When I press the key with SHIFT I get "Ä" which is fine.

Is it correct that moving the cursor via the keyboard requires left SHIFT to be used? Right SHIFT doesn't influence the cursor movement.

Regards,
Henning

**Comment by dabonetn** [comment]
Ok, I just rewote the readme a little to explain the hybrid keys better.

Left shift is treated as a special modifier for the these keys.

Cursor L/R, F7, F1, F3, F5, Cursor U/D, and Restore.  

right shift isn't.

The CTRL key is treated as a special modifier for the following keys.

F7, F1, F3, F5, Restore.


I just upgraded computers, so I'm reinstalling the dev tools, and trying to find the correct keymap for your special character. It doesn't exist for me. if you look at the keydefs.h, that's what's currently available to me.

**Comment by dabonetn** [comment]
For a quick test please edit line 88 in the keydefs.h file from

#define KEY_SEMICOLON 0x3B


to


#define KEY_SEMICOLON 0x2C





Thanks.

**Comment by hpingel** [comment]
Hi, This doesn't change the behaviour when pressing the key ";" but it changes the behaviour of the key ":" where I now get the following chars on screen: (unshifted:) , (shifted:) ;

Thank you!

**Comment by hpingel** [comment]
I think the challenge is that we talk about three keyboard layouts at the same time
a) C64 (here the Semicolon is two positions right form key "L")
b) Standard KB United States (here the Semicolon is on the right side of key "L")
c) German keyboard (here the expected ä/Ä is two positions on the right of key "L")

So I think we need to change the value of KEY_QUOTE.

But now I read a bit on the net about Arduino Leonardo + German "umlauts" and it seems to be more tricky. Maybe let me understand that first before "demanding" a solution. It seems that the keyboard lib is not perfectly prepared for special characters.

I guess if one uses C64USBKey together with VICE no one will notice a bug. It's only once you decide to use C64USBKey for word processing on Windows.

Also: Most of the German umlauts work fine in C64USBKey. I have no problems with ö/Ö/ü/Ü/ß at all, it is just the one key for ä/Ä that has a small bug.

By the way: I'm using Arduino software 1.8.9.

**Comment by dabonetn** [comment]
Fixed, 

To get the correct key, uncomment the line 

// #include "keydefs-german.h"                      // Uncomment to fix German umlaut รค/ key 

to be 

#include "keydefs-german.h"                      // Uncomment to fix German umlaut รค/ key
