### ISSUE TITLE
cannot set the characters exactly as labelled on the original keyboard

### ISSUE THREAD

**Issue by theshinyknight** [dabonetn/C64USBKey#7]
Not sure if there is a way to fix this, but beside some keys that are required in general, like ESC, TAB, backslash and the braces; I can't seem to find a way to assign all the other keys exactly as they are printed on the keys.
Is this a limitation of how the Arduino keyboard library works?

**Comment by dabonetn** [comment]
As for changing key assignments, if you look at lines 97-104 those are the key definitions, with the commodore keys listed after the comments per line.

Supported keys and labels are listed in the keydefs.h file.

Shifted keys are listed underneath that.

You can change the shifted keys by changing these lines.

int HybridKey=17;                                                             // Position of the Hybrid Select key in the keymap, Left Shift = 17, Right Shift = 64
int HybridKey2=72;                                                            // Position of the Hybrid2 Select key in the keymap, CTRL = 72

**Comment by gpg342** [comment]
Hi - great work and really helpful in making use of a C64 breadbin.

As the previous comment -- I would like to restore the C64 keys.

I can move the key mapping to restore things like the + and - keys.

Where things go a bit flaky (and its bound to be me) is when I want to alter the shifted keys.

For example - the original C64 has Shift-6 as the ampersand, no the caret (as on the pc).... so I:

(1) Defined the ampersand as KEY_AMP 0x26 in the keydefs.h file
(2) Added KEY_AMP into  Hybridkeys 
(3) Added if (keyDown[HybridKey]&&keyDown[24])  {Keyboard.release (keyDown[HybridKey]);keyDown[keyPos]=Hybridkeys[8];}

Where 24 is Key_6
Hybridkeys[8] = KEY_AMP


All compiles and loads as expected.

However, this does not change the behavior of the SHIFT-6 key, which continues to display the caret ^.

I know I must be doing something wrong.

Any pointers?

Cheers
Glen

**Comment by dabonetn** [comment]
That's not a function of the keyboard library, but the computer it's hooked up to. 
How shifted characters are handled is by the computer/os. That's why you have to use the keymap files with vice.

Look at something like this.

https://www.makeuseof.com/tag/create-custom-keyboard-layout-windows/

**Comment by gpg342** [comment]
Awesome - that makes sense, I can work with that.

Just for my sanity then  -- I cant trap for shifted characters with:
>>  if (keyDown[HybridKey]&&keyDown[24])

Is that an OS thing or an arduino library thing.

Thank you for you support -- greatly appreciated.

GLEN
